version: '3'
services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./.docker-data/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=python3-service-test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
