version: '3'
services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./.docker-data/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=python3-service-test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - services

  app:
    build:
      context: .
    ports:
      - "80:8080"
    volumes:
      - "./.docker-data/postgres:/var/lib/postgresql/data"
    environment:
      - DB_HOST=db
      - DB_NAME=python3-service-test
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    networks:
      - services

networks:
  services: {}